// List event-field string for each know warning
export const knownWarningTypes = [
  // meteorological warnings
  'Severe weather warning',
  'Wind and waves warning',
  'High tide warning',
  'Disturbance advisory',
  'Disturbance watch',
  'Disturbance warning',
  'Tropical depression advisory',
  'Tropical depression watch',
  'Tropical depression warning',
  'Tropical storm advisory',
  'Tropical storm watch',
  'Tropical storm warning',
  'Hurricane advisory',
  'Hurricane watch',
  'Hurricane warning',
  'Post-tropical cyclone advisory',
  'Post-tropical cyclone watch',
  'Post-tropical cyclone warning',
  'Landslide warning',
  'Forest fire warning',
  'Low temperature advisory',
  'Low temperature watch',
  'Low temperature warning',
  'High temperature advisory',
  'High temperature watch',
  'High temperature warning',
  'Rainfall advisory',
  'Rainfall watch',
  'Rainfall warning',
  // hydrological warnings
  'Flash flood advisory',
  'Flash flood watch',
  'Flash flood warning',
  'Low river level advisory',
  'Low river level watch',
  'Low river level warning',
  'High river level advisory',
  'High river level watch',
  'High river level warning',
  'Flood routing advisory',
  'Flood routing watch',
  'Flood routing warning',
  'Flash flood advisory due reservoir water discharge',
  'Flash flood watch due reservoir water discharge',
  'Flash flood warning due reservoir water discharge',
  'River flooding warning'
] as const;

export const severityList = ['', 'Moderate', 'Severe', 'Extreme'] as const;
